import {
    Button,
    HorizontalBox,
    VerticalBox,
    AboutSlint
} from "std-widgets.slint";

export component AppWindow inherits Window {
    default-font-family: "Arial";
    default-font-size: 45px;

    VerticalBox {
        alignment: center;
        spacing: 15px;

        HorizontalBox {
            alignment: center;
            spacing: 15px;

            header := Text {
                text: "";
            }
        }

        b1 := Button {
            text: "Button 1";
            clicked => {
                header.text = "Button 1 clicked";
            }
        }

        b2 := Button {
            text: "Button 2";
            clicked => {
                header.text = "Button 2 clicked";
            }
        }

        b3 := Button {
            text: "Button 3";
            clicked => {
                header.text = "Button 3 clicked";
            }
        }

        b4 := Button {
            text: "Button 4";
            clicked => {
                header.text = "Button 4 clicked";
            }
        }
     }
}
